//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRoleResourceMS_Beat.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserManageAspEntities : DbContext
    {
        public UserManageAspEntities()
            : base("name=UserManageAspEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Resource> T_Resource { get; set; }
        public DbSet<T_Role> T_Role { get; set; }
        public DbSet<T_RoleResource> T_RoleResource { get; set; }
        public DbSet<T_User> T_User { get; set; }
        public DbSet<T_UserRole> T_UserRole { get; set; }
    }
}
