//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRoleResourceMS_Beat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Resource
    {
        public T_Resource()
        {
            this.T_RoleResource = new HashSet<T_RoleResource>();
        }
    
        public int ResourceID { get; set; }
        public string ResourceName { get; set; }
        public string ResDescription { get; set; }
        public string CreateOperatorID { get; set; }
        public string CreateOperatorName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string ModiOperatorID { get; set; }
        public string ModiOperatorName { get; set; }
        public System.DateTime ModiTime { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<T_RoleResource> T_RoleResource { get; set; }
    }
}
